### ISSUE TITLE
feature request: auto-save

### ISSUE THREAD

**Issue by TZornG** [SteffenBauer/PocketPuzzles#10] opened 2020-12-02 13:16 UTC
Thanks again for this cool app. I've posted in mobile reads forum before with a different user name. But let's collect issues rather here on Github.

You have a menu item "save and exit" which works as expected. But ever so often I put the reader aside to do something else and when I take it back the reader has powered down. Game status gone. Could you implement an auto-save which preserves the last game status before exiting the app or powering down?

**Comment by SteffenBauer** [comment] 2020-12-02 15:24
Makes sense. I will check what exactly happens when the app receives an `EVT_EXIT` event from the OS, and if it is sufficient to save the game state at that point.

**Comment by SteffenBauer** [comment] 2020-12-02 15:45
Just made some tests with manually closing the app via the task manager, results indicate that this indeed could work.

Can you check the following with the current app, with your current usage pattern as I understand it? 

1. Open the app to the game chooser. 
2. Mark some additional games as favorite. 
3. Don't close the app, put your reader aside, wait until it powers down.
4. Repower the reader, launch the app.
5. Check if the additional games are still marked as favorite or not.

If the new games are marked as favorite, then the app has indeed catched `EVT_EXIT` correctly, and I just need to add an additional game serialization.

**Comment by TZornG** [comment] 2020-12-02 17:12
Followed your steps above and the new games are still marked as favorites after restart.

**Comment by SteffenBauer** [comment] 2020-12-02 22:08
I added explicit game / chooser state serialisation when the app receives an external EXIT signal. Please test releases/SGTPuzzles.app if the app now works as requested. 

When the device shuts down or the app is closed forcefully by task manager while a game is currently going on, and upon reboot the app restarted again, it should now resume the game in its last state.

Please report here if the issue is resolved successfully with this change, I will then release v 0.6.1 and close this issue.

**Comment by TZornG** [comment] 2020-12-03 09:26
I tested closing the app in the task manager and letting the reader power off by itself. In both cases the previous game status was successfully restored after restarting the app. I'd say issue closed.

When you have too much spare time - let's say during some quarantine ;-) - you may want to add saving the status per game. But I don't want to appear too demanding here. Thanks again for this great app (stock Sudoku got terribly boring over time).

**Comment by SteffenBauer** [comment] 2020-12-03 09:31
Solved by https://github.com/SteffenBauer/PocketPuzzles/commit/de5d5f3247314364aacfe3ba89150e2371e63678

**Closed by SteffenBauer** 2020-12-03 09:31 UTC
